### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by mathbionerd** [hackseq/2016_project_6#1]
Howdy all, and thank you for your interest in this hackseq! 

I'm hoping we can all introduce ourselves  ourselves and start some conversations before we meet in Vancouver. 

I am an assistant professor at Arizona State University: [http://www.wilsonsayreslab.org](http://www.wilsonsayreslab.org). My research interests include understanding sex-biased genome evolution and how demography and selection shape genome-wide patterns of variation. In particular, my work has focused on characterizing evolution of the sex chromosomes across species. 

I'm really looking forward to meet you all! In another week or so, I'll share some suggested readings ahead of our hackseq. 

Best,
Melissa

**Comment by thw17** [comment]
Hi everyone,

I'm a postdoc at Arizona State University working with Melissa.  I'm generally interested in reconstructing aspects of population and species history (speciation, adaptation, demographic events, etc.) using genomic data.  Because of their inheritance patterns, sex chromosomes are pretty central to what I do. While I work across a range of taxa, my research primarily involves human and nonhuman primates or reptiles.

Looking forward to meeting everyone!

Cheers,
Tim

**Comment by tanyaphung** [comment]
Hi everyone,

I'm a graduate student at UCLA and am working with Kirk Lohmueller. My research interest includes understanding how different evolutionary processes shape the genetic variation observed within species, between species, on the autosomes and the sex chromosomes. 

I'm very excited for this opportunity to learn from all of you!

Best,
Tanya

**Comment by whitneywhitford** [comment]
Hey,

I'm a PhD candidate at the University of Auckland, with Jessie Jacobsen and Russell Snell. I'm interested in the genetic causes of human disease, with my project focusing on identifying chromosomal structural rearrangements (mainly copy number variants) from whole genome sequence data from individuals with neurodevelopmental disorders. 

Although I don't focus on sex chromosomes, a large part of my research at the moment is using platforms which identify copy number changes in sequence data.

Thanks,
Whitney

**Comment by ekarlins** [comment]
Hello fellow hackers,
I'm a bioinformatics analyst at the U.S. National Cancer Institute (part of the NIH) supporting the DCEG division.  The "E" stands for epidemiology, so most of the PIs I work with are epidemiologists.  I work closely with several investigators working on pediatric cancers (osteosarcoma, retinoblastoma, second cancers after pediatric cancer).  Most of the work I do is GWAS, exome sequencing analysis, and DNA methylation analysis, though I have a small role in a lot of projects.

I was involved in one study on chrX mosaicism and my ASHG poster is on attempting to discover mosaic point mutations using exome sequencing data, so I do have interests that overlap with our hackseq project.  I'm also interested in tumor clonal evolution, though haven't worked specifically on this.

My scripting language of choice is python and I use R frequently as well, though I often use freely available commandline tools if there's one available that suits my purposes.  I enjoy working using a compute cluster where having access to mass parallelization means that my code doesn't need to be perfectly optimized.  

I've been with NCI for two years, prior to that I was in a lab in another NIH institute (NHGRI) for 10 years.  The lab worked on the genetics of human prostate cancer and many canine genetics projects.  I started working there as a lab technician, but transitioned to bioinformatics analysis by the time I left.

Looking forward to seeing you all in Vancouver!
Eric

**Comment by BrunoGrandePhD** [comment]
Hello Team 9! 

I'm a PhD candidate with Dr. Ryan Morin at Simon Fraser University in Vancouver. My main project focuses on the genetic characterization of Burkitt lymphoma, an aggressive paediatric cancer most common in Equatorial Africa. I'm leveraging sequencing to investigate the landscape of somatic mutations (whole genome sequencing) and their effects on the transcriptome (mRNA and miRNA sequencing) in order to identify new targets for therapy. While my research doesn't focus on the sex chromosomes, I'm eager to learn more about them through this project! 

I'm also one of the Hackseq organizers. I look forward to meet you all in person and work alongside you at Hackseq! I don't know about you, but this will be my first hackathon. It's actually part of the reason I agreed to help organize the event: I wanted to organize something that I could participate in, and a genomics hackathon seemed perfectly relevant. 

Python has been my go-to scripting language since I started grad school. However, over the past year or so, I've learned enough R that it has replaced Python when it comes to handling anything tabular or plotting. 

Hackseq starts two weeks from today. See you all then!

Peace ✌️ 
Bruno
